### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'ndims' in conv_block

### ISSUE THREAD

**Issue by Aenas11** [mckinziebrandon/ai-with-tensorflow#1]
Hi I am trying to follow "https://www.safaribooksonline.com/videos/learn-artificial-intelligence" but getting above error in "cifar10_model.py" on line #42 in cifar10_model.py. What am i doing wrong?

**Comment by mckinziebrandon** [comment]
Hello, can you show me how you're running the code? Seems like the error is coming from TensorFlow, which means either (a) the arguments are being passed in an unexpected way, or (b) you may be using a version of TF incompatible with this repository. I'd assume the more likely of the two is (a). 

If I see how you're running it / what parameters you're using, I can provide more detailed help.

**Comment by mckinziebrandon** [comment]
Is this resolved? Will close soon if no response.
