### ISSUE TITLE
ValueError in dataset.py

### ISSUE THREAD

**Issue by simonsays1980** [mckinziebrandon/ai-with-tensorflow#2]
dataset.py is raising the following error in 'padded_batch()':

ValueError: The padded shape (20,) is not compatible with the corresponding input component shape ().

This can be fixed by adding the colon before 'self.params.max_seq_len' at line 35 in dataset.py (return value of 'parser()' method).

**Comment by mckinziebrandon** [comment]
You are correct, good catch! Happy to accept a PR if you want to add that change.

**Comment by simonsays1980** [comment]
I will. Give me some time to set everything up. Right now I am working on an isolated local copy of the code.

**Comment by mckinziebrandon** [comment]
Closing. Resolved by #3.
